import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { AlertTriangle } from "lucide-react";

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navbar />
      <main className="flex-1 max-w-3xl mx-auto px-4 py-16 w-full">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-lg bg-destructive/10 text-destructive flex items-center justify-center flex-shrink-0">
            <AlertTriangle className="w-5 h-5" />
          </div>
          <h1 className="text-4xl font-extrabold">Disclaimer</h1>
        </div>
        <p className="text-muted-foreground text-lg mb-10">Last updated: March 2026</p>

        <div className="bg-destructive/5 border border-destructive/20 rounded-xl p-6 mb-10">
          <h2 className="font-bold text-destructive text-xl mb-2">⚠ Important Legal Notice</h2>
          <p className="text-foreground/80 leading-relaxed">
            Certificates generated by Medical Certificate Generator are <strong>not legally valid medical documents</strong>. They are provided
            for educational, demonstration, and non-fraudulent purposes only. Using them as real documents is illegal.
          </p>
        </div>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4">Not Medical Advice</h2>
          <p className="text-foreground/80 leading-relaxed mb-3">
            Nothing on this website or in any certificate generated constitutes medical advice, diagnosis, or treatment.
            The diagnoses, medications, and medical information shown in templates are fictional and should not be relied
            upon for any health-related decisions.
          </p>
          <p className="text-foreground/80 leading-relaxed">
            If you have a medical concern, please consult a licensed, qualified healthcare professional.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4">Not Legal Documents</h2>
          <p className="text-foreground/80 leading-relaxed mb-3">
            Generated certificates are entirely fictional. They are not:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-2 text-foreground/80 mb-4">
            <li>Recognized by employers as valid sick leave documentation</li>
            <li>Accepted by insurance companies as proof of medical conditions</li>
            <li>Recognized by government agencies as official health records</li>
            <li>Valid in any court or legal proceeding</li>
            <li>Issued or endorsed by any real hospital, clinic, or doctor</li>
          </ul>
          <p className="text-foreground/80 leading-relaxed">
            Presenting a generated certificate as genuine to any of the above constitutes fraud and is a criminal offense
            in most jurisdictions.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4">No Liability for Misuse</h2>
          <p className="text-foreground/80 leading-relaxed mb-3">
            Medical Certificate Generator, its owner Ziven Borceg, and any associated contributors accept zero liability for:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-2 text-foreground/80">
            <li>Criminal charges or civil penalties resulting from fraudulent use</li>
            <li>Harm caused to third parties who are deceived by generated certificates</li>
            <li>Loss of employment, benefits, or legal standing resulting from misuse</li>
            <li>Any indirect, consequential, or incidental damages of any kind</li>
          </ul>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4">Permitted Use Cases</h2>
          <p className="text-foreground/80 leading-relaxed mb-3">This tool is appropriate for:</p>
          <ul className="list-disc list-inside space-y-2 ml-2 text-foreground/80">
            <li>Building and testing healthcare software applications</li>
            <li>Creating UI/UX mockups and design prototypes</li>
            <li>Academic study of document formats</li>
            <li>Educational demonstrations in training programs</li>
            <li>Film, television, and theatrical props (clearly fictional contexts)</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4">Contact</h2>
          <p className="text-foreground/80 leading-relaxed">
            If you have questions or want to report misuse of this tool, please{" "}
            <a href="/contact" className="text-primary hover:underline">contact us</a>.
          </p>
        </section>
      </main>
      <Footer />
    </div>
  );
}
