import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <section className="mb-10">
    <h2 className="text-2xl font-bold mb-4">{title}</h2>
    <div className="text-foreground/80 leading-relaxed space-y-3">{children}</div>
  </section>
);

export default function Terms() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navbar />
      <main className="flex-1 max-w-3xl mx-auto px-4 py-16 w-full">
        <h1 className="text-4xl font-extrabold mb-2">Terms & Conditions</h1>
        <p className="text-muted-foreground mb-10">Last updated: March 2026</p>

        <Section title="Acceptance of Terms">
          <p>By accessing or using Medical Certificate Generator ("the Service") at medicalcertificategenerator.co.in, you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Service.</p>
        </Section>

        <Section title="Purpose of the Service">
          <p>Medical Certificate Generator is designed exclusively for:</p>
          <ul className="list-disc list-inside space-y-2 ml-2">
            <li>Educational demonstrations and classroom training</li>
            <li>UI/UX design mockups and prototyping</li>
            <li>Software testing and staging environments</li>
            <li>Academic projects and research</li>
            <li>Entertainment and creative projects (e.g., films, plays, fiction)</li>
          </ul>
          <p><strong>The Service is NOT intended for, and must NOT be used for, creating fraudulent documents.</strong></p>
        </Section>

        <Section title="Download & Access">
          <p>Medical Certificate Generator is a <strong>100% digital, browser-based tool</strong>. There are no physical products, no shipping fees, and no delivery wait times. All document styling, canvas rendering, and downloads are processed entirely client-side in your web browser.</p>
          <p>By clicking the "Download" or "Print" buttons, you generate and download a digital file (such as a PNG or PDF) directly to your local device. Because the Service is completely free and processes all generation locally, there are no payment methods, no order processing pipelines, and no shipping required.</p>
        </Section>

        <Section title="Prohibited Uses">
          <p>You are strictly prohibited from using this Service to:</p>
          <ul className="list-disc list-inside space-y-2 ml-2">
            <li>Submit false medical certificates to employers, schools, insurance companies, or government bodies</li>
            <li>Obtain medical leave, insurance payouts, or benefits fraudulently</li>
            <li>Impersonate doctors, hospitals, or medical institutions</li>
            <li>Commit identity fraud or any other form of deception</li>
            <li>Resell or redistribute generated certificates as authentic documents</li>
            <li>Use the Service in any manner that violates applicable laws or regulations</li>
          </ul>
          <p>Violation of these prohibitions may result in civil and criminal liability. We cooperate with law enforcement in investigations of fraudulent document use.</p>
        </Section>

        <Section title="No Legal Validity">
          <p>All certificates generated by this Service are fictional. They bear no legal validity and are not recognized by any medical authority, employer, government, or insurance provider. No generated certificate should be presented as authentic to any person or organization.</p>
        </Section>

        <Section title="User Responsibility">
          <p>You, the user, bear full legal and ethical responsibility for any certificates you generate and how they are used. We, Medical Certificate Generator and Ziven Borceg, accept no liability for:</p>
          <ul className="list-disc list-inside space-y-2 ml-2">
            <li>Any direct, indirect, or consequential damages arising from misuse</li>
            <li>Legal penalties, fines, or criminal charges resulting from your use</li>
            <li>Actions taken by third parties based on generated certificates</li>
          </ul>
        </Section>

        <Section title="Intellectual Property">
          <p>All code, design, templates, and content on this website are the intellectual property of Ziven Borceg and Medical Certificate Generator. You may not copy, reproduce, distribute, or create derivative works without explicit written permission.</p>
        </Section>

        <Section title="Service Availability">
          <p>We make no guarantees about service uptime or availability. We may modify, suspend, or discontinue the Service at any time without notice.</p>
        </Section>

        <Section title="Modifications to Terms">
          <p>We reserve the right to modify these Terms at any time. Continued use of the Service after modifications constitutes acceptance of the new Terms.</p>
        </Section>

        <Section title="Governing Law">
          <p>These Terms are governed by and construed in accordance with applicable law. Any disputes shall be resolved in the jurisdiction where the service operator resides.</p>
        </Section>

        <div id="disclaimer" className="scroll-mt-20">
          <Section title="Disclaimer & Legal Notices">
            <div className="bg-destructive/5 border border-destructive/20 rounded-xl p-6 mb-6">
              <h3 className="font-bold text-destructive text-lg mb-2">⚠ Important Legal Notice</h3>
              <p className="text-foreground/80 leading-relaxed text-sm">
                Certificates generated by Medical Certificate Generator are <strong>not legally valid medical documents</strong>. They are provided for educational, demonstration, and non-fraudulent purposes only. Using them as real documents is illegal and strictly prohibited.
              </p>
            </div>

            <div className="space-y-6">
              <div>
                <h3 className="font-bold text-lg mb-2 text-foreground">Not Medical Advice</h3>
                <p className="text-foreground/80 leading-relaxed text-sm">
                  Nothing on this website or in any certificate generated constitutes medical advice, diagnosis, or treatment. The diagnoses, medications, and medical information shown in templates are fictional and should not be relied upon for any health-related decisions. If you have a medical concern, please consult a licensed, qualified healthcare professional.
                </p>
              </div>

              <div>
                <h3 className="font-bold text-lg mb-2 text-foreground">Not Legal Documents</h3>
                <p className="text-foreground/80 leading-relaxed text-sm">
                  Generated certificates are entirely fictional. They are not:
                </p>
                <ul className="list-disc list-inside space-y-1.5 ml-4 text-foreground/80 text-sm mb-3">
                  <li>Recognized by employers as valid sick leave documentation</li>
                  <li>Accepted by insurance companies as proof of medical conditions</li>
                  <li>Recognized by government agencies as official health records</li>
                  <li>Valid in any court or legal proceeding</li>
                  <li>Issued or endorsed by any real hospital, clinic, or doctor</li>
                </ul>
                <p className="text-foreground/80 leading-relaxed text-sm">
                  Presenting a generated certificate as genuine to any of the above constitutes fraud and is a criminal offense in most jurisdictions.
                </p>
              </div>

              <div>
                <h3 className="font-bold text-lg mb-2 text-foreground">No Liability for Misuse</h3>
                <p className="text-foreground/80 leading-relaxed text-sm font-medium text-foreground">
                  Medical Certificate Generator, its owner Ziven Borceg, and any associated contributors accept zero liability for:
                </p>
                <ul className="list-disc list-inside space-y-1.5 ml-4 text-foreground/80 text-sm">
                  <li>Criminal charges or civil penalties resulting from fraudulent use</li>
                  <li>Harm caused to third parties who are deceived by generated certificates</li>
                  <li>Loss of employment, benefits, or legal standing resulting from misuse</li>
                  <li>Any indirect, consequential, or incidental damages of any kind</li>
                </ul>
              </div>

              <div>
                <h3 className="font-bold text-lg mb-2 text-foreground">Permitted Use Cases</h3>
                <p className="text-foreground/80 leading-relaxed text-sm">This tool is appropriate for:</p>
                <ul className="list-disc list-inside space-y-1.5 ml-4 text-foreground/80 text-sm">
                  <li>Building and testing healthcare software applications</li>
                  <li>Creating UI/UX mockups and design prototypes</li>
                  <li>Academic study of document formats</li>
                  <li>Educational demonstrations in training programs</li>
                  <li>Film, television, and theatrical props (within clearly fictional contexts)</li>
                </ul>
              </div>
            </div>
          </Section>
        </div>

        <Section title="Bharatiya Nyaya Sanhita (BNS) 2023 — Applicable Provisions">
          <p>
            The Bharatiya Nyaya Sanhita (BNS) 2023 (which replaced the Indian Penal Code, or IPC) contains provisions directly applicable to fraudulent document use. Under Section 336 (forgery), Section 340 (using forged documents), and Section 318 (cheating), individuals who present generated medical certificates as genuine to employers, educational institutions, or government bodies can face serious criminal charges. Penalties include imprisonment up to 2 years, hefty fines, or both. Please note that this is NOT legal advice — consult a licensed advocate for specific legal situations.
          </p>
        </Section>

        <Section title="Contact">
          <p>For questions about these Terms, please <a href="/contact" className="text-primary hover:underline">contact us</a>.</p>
        </Section>
      </main>
      <Footer />
    </div>
  );
}
