import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <section className="mb-10">
    <h2 className="text-2xl font-bold mb-4">{title}</h2>
    <div className="text-foreground/80 leading-relaxed space-y-3">{children}</div>
  </section>
);

export default function Terms() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navbar />
      <main className="flex-1 max-w-3xl mx-auto px-4 py-16 w-full">
        <h1 className="text-4xl font-extrabold mb-2">Terms & Conditions</h1>
        <p className="text-muted-foreground mb-10">Last updated: March 2026</p>

        <Section title="Acceptance of Terms">
          <p>By accessing or using Medical Certificate Generator ("the Service") at medicalcertificategenerator.co.in, you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Service.</p>
        </Section>

        <Section title="Purpose of the Service">
          <p>Medical Certificate Generator is designed exclusively for:</p>
          <ul className="list-disc list-inside space-y-2 ml-2">
            <li>Educational demonstrations and classroom training</li>
            <li>UI/UX design mockups and prototyping</li>
            <li>Software testing and staging environments</li>
            <li>Academic projects and research</li>
            <li>Entertainment and creative projects (e.g., films, plays, fiction)</li>
          </ul>
          <p><strong>The Service is NOT intended for, and must NOT be used for, creating fraudulent documents.</strong></p>
        </Section>

        <Section title="Prohibited Uses">
          <p>You are strictly prohibited from using this Service to:</p>
          <ul className="list-disc list-inside space-y-2 ml-2">
            <li>Submit false medical certificates to employers, schools, insurance companies, or government bodies</li>
            <li>Obtain medical leave, insurance payouts, or benefits fraudulently</li>
            <li>Impersonate doctors, hospitals, or medical institutions</li>
            <li>Commit identity fraud or any other form of deception</li>
            <li>Resell or redistribute generated certificates as authentic documents</li>
            <li>Use the Service in any manner that violates applicable laws or regulations</li>
          </ul>
          <p>Violation of these prohibitions may result in civil and criminal liability. We cooperate with law enforcement in investigations of fraudulent document use.</p>
        </Section>

        <Section title="No Legal Validity">
          <p>All certificates generated by this Service are fictional. They bear no legal validity and are not recognized by any medical authority, employer, government, or insurance provider. No generated certificate should be presented as authentic to any person or organization.</p>
        </Section>

        <Section title="User Responsibility">
          <p>You, the user, bear full legal and ethical responsibility for any certificates you generate and how they are used. We, Medical Certificate Generator and Ziven Borceg, accept no liability for:</p>
          <ul className="list-disc list-inside space-y-2 ml-2">
            <li>Any direct, indirect, or consequential damages arising from misuse</li>
            <li>Legal penalties, fines, or criminal charges resulting from your use</li>
            <li>Actions taken by third parties based on generated certificates</li>
          </ul>
        </Section>

        <Section title="Intellectual Property">
          <p>All code, design, templates, and content on this website are the intellectual property of Ziven Borceg and Medical Certificate Generator. You may not copy, reproduce, distribute, or create derivative works without explicit written permission.</p>
        </Section>

        <Section title="Service Availability">
          <p>We make no guarantees about service uptime or availability. We may modify, suspend, or discontinue the Service at any time without notice.</p>
        </Section>

        <Section title="Modifications to Terms">
          <p>We reserve the right to modify these Terms at any time. Continued use of the Service after modifications constitutes acceptance of the new Terms.</p>
        </Section>

        <Section title="Governing Law">
          <p>These Terms are governed by and construed in accordance with applicable law. Any disputes shall be resolved in the jurisdiction where the service operator resides.</p>
        </Section>

        <Section title="Contact">
          <p>For questions about these Terms, please <a href="/contact" className="text-primary hover:underline">contact us</a>.</p>
        </Section>
      </main>
      <Footer />
    </div>
  );
}
