import { Metadata } from "next";
import Generator from "@/views/Generator";
import { TEMPLATES } from "@/types/certificate";
import { TemplateInfoSection } from "@/components/certificate/TemplateInfoSection";

const BASE_URL = "https://medicalcertificategenerator.co.in";

export function generateStaticParams() {
  return TEMPLATES.map((t) => ({ templateId: t.id }));
}

export async function generateMetadata({ params }: { params: Promise<{ templateId: string }> }): Promise<Metadata> {
  const { templateId } = await params;
  const template = TEMPLATES.find((t) => t.id === templateId);
  if (!template) return { title: "Certificate Generator | Medical Certificate Generator" };

  const url = `${BASE_URL}/generator/${template.id}`;
  const title = `${template.name} — Free Medical Certificate Generator`;
  const description = `Generate a ${template.name} instantly. ${template.description} Free PNG & PDF download, fully customisable online.`;

  return {
    // Generator page titles contain 'Medical Certificate', use absolute to skip suffix
    title: { absolute: title },
    description,
    alternates: { canonical: url },
    openGraph: {
      type: "website",
      url,
      title,
      description,
      images: [{ url: template.previewImage, width: 800, height: 1067, alt: template.name }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [template.previewImage],
    },
  };
}

export default async function GeneratorPage({ params }: { params: Promise<{ templateId: string }> }) {
  const { templateId } = await params;
  const template = TEMPLATES.find((t) => t.id === templateId);

  const faqSchema = template ? {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": `What type of clinic does the ${template.name} template represent?`,
        "acceptedAnswer": {
          "@type": "Answer",
          "text": template.templateContent?.clinicType 
            ? `The ${template.name} template is based on a ${template.templateContent.clinicType} format, commonly used in ${template.templateContent.indiaRegion}.`
            : `The ${template.name} is one of 15+ authentic Indian medical certificate templates available on this generator.`
        }
      },
      {
        "@type": "Question",
        "name": `What is the ${template.name} medical certificate template best used for?`,
        "acceptedAnswer": {
          "@type": "Answer",
          "text": template.templateContent?.bestFor?.join(", ") 
            ?? `The ${template.name} template is suitable for standard sick leave and medical documentation in a sample or demo context.`
        }
      },
      {
        "@type": "Question",
        "name": `What fields does the ${template.name} certificate include?`,
        "acceptedAnswer": {
          "@type": "Answer",
          "text": template.templateContent?.fieldsIncluded?.join(", ")
            ?? `This template includes standard medical certificate fields: patient name, diagnosis, rest period, doctor details, and clinic information.`
        }
      },
      {
        "@type": "Question",
        "name": "Is the generated certificate legally valid for submitting to my employer?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "No. Certificates generated by this tool are sample documents for educational, demonstration, and software testing purposes only. They have no legal validity. Submitting a generated certificate as genuine to any employer, institution, or government body is a criminal offence under the Bharatiya Nyaya Sanhita (BNS) 2023. For a legally valid certificate, consult an NMC-registered medical practitioner."
        }
      },
      {
        "@type": "Question",
        "name": "Is my data saved when I use this generator?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "No. All certificate generation happens entirely in your browser using JavaScript. No patient name, diagnosis, doctor details, or any other data you enter is transmitted to or stored on our servers. Your privacy is completely protected."
        }
      }
    ]
  } : null;

  return (
    <>
      {faqSchema && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
        />
      )}
      <Generator />
      {template && <TemplateInfoSection template={template} />}
    </>
  );
}
