import Link from "next/link";
import type { BlogPostData } from "./blogTypes";

const InternalLink = ({ href, children }: { href: string; children: React.ReactNode }) => (
  <Link href={href} className="text-primary font-medium hover:underline">{children}</Link>
);

const Disclaimer = () => (
  <p className="text-sm text-muted-foreground border-l-4 border-border pl-4 italic mt-6">
    Disclaimer: This article is for educational and informational purposes only. Certificates generated by Medical Certificate Generator are specimen documents for demo and educational use — not legally valid medical documents. Always obtain genuine certificates from a registered medical practitioner.
  </p>
);

export const BLOG_POSTS_PART4: BlogPostData[] = [
  // ─── ARTICLE 5 ──────────────────────────────────────────────────────────────
  {
    slug: "medical-certificate-maternity-leave",
    title: "Medical Certificate for Maternity Leave: What You Need and How to Get It",
    metaDescription: "A complete guide to medical certificates for maternity leave in India — what documents your employer needs, when to submit, your legal rights under the Maternity Benefit Act, and what the certificate must contain.",
    category: "Medical Certificates",
    date: "April 2026",
    readTime: "10 min read",
    tags: ["Maternity Leave", "Medical Certificate", "Pregnancy", "India", "Maternity Benefit Act"],
    author: "Ziven Borceg",
    content: (
      <div className="space-y-6 text-foreground/80 leading-relaxed">
        <p className="text-lg font-medium text-foreground">
          You're expecting, and the last thing you want to deal with is confusing paperwork. But getting your maternity leave documentation right matters — it protects your paid leave, your job, and your legal rights. This guide walks you through exactly what medical certificate your employer needs, when to submit it, and what it must contain to avoid any hassle.
        </p>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Maternity Leave in India: Your Legal Rights First</h2>
          <p>Before we get to the certificate, let's understand your rights. The <strong>Maternity Benefit Act, 1961 (amended 2017)</strong> entitles eligible women employees to:</p>
          <ul className="list-disc list-inside space-y-2 ml-4 mt-3">
            <li><strong>26 weeks</strong> of paid maternity leave for the first two children</li>
            <li><strong>12 weeks</strong> of paid maternity leave from the third child onwards</li>
            <li><strong>12 weeks</strong> of paid leave for adoptive mothers (children below 3 months) and commissioning mothers</li>
            <li><strong>6 weeks</strong> of leave in case of miscarriage or medical termination of pregnancy</li>
          </ul>
          <p className="mt-3">These rights apply to establishments with 10 or more employees. The leave is generally taken from 8 weeks before the expected delivery date + post-delivery rest.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">What Medical Certificate Is Required for Maternity Leave?</h2>
          <p>The Maternity Benefit Act does not mandate a single specific certificate format — but most HR departments in India ask for one or more of the following:</p>
          <div className="space-y-3 mt-3">
            {[
              { title: "Pregnancy Certificate / Confirmation Letter", desc: "Issued by your gynaecologist or obstetrician, confirming the pregnancy and the expected date of delivery (EDD). Usually provided after the first or second trimester scan." },
              { title: "Pre-Delivery Leave Certificate", desc: "Certifies that you are pregnant and advises pre-natal leave from a specific date (usually 8 weeks before EDD). Issued by your treating gynaecologist." },
              { title: "Post-Delivery Certificate", desc: "Confirms the date of actual delivery (for live birth) or miscarriage. Usually the hospital discharge summary serves this purpose." },
              { title: "Fitness Certificate for Return to Work", desc: "Some employers require a fitness certificate before you return to work. Issued by your doctor confirming you are medically fit to resume duties." },
            ].map(d => (
              <div key={d.title} className="bg-card border border-border rounded-xl p-4">
                <p className="font-semibold text-foreground mb-1">{d.title}</p>
                <p className="text-sm text-muted-foreground">{d.desc}</p>
              </div>
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">What the Maternity Medical Certificate Must Contain</h2>
          <p>A maternity leave medical certificate should include:</p>
          <ul className="list-disc list-inside space-y-2 ml-4 mt-3">
            <li>Doctor's name, qualifications (MBBS, MD/DNB-Obstetrics & Gynaecology), and registration number</li>
            <li>Clinic or hospital name and address</li>
            <li>Patient's full name, age, and date of examination</li>
            <li>Confirmation of pregnancy (gestational age if available)</li>
            <li>Expected Date of Delivery (EDD)</li>
            <li>Recommended pre-delivery leave start date</li>
            <li>Doctor's signature and clinic stamp</li>
          </ul>
          <div className="bg-muted/40 rounded-xl p-4 font-mono text-sm border border-border mt-4">
            <p className="font-semibold not-italic mb-2 text-foreground">Sample phrasing:</p>
            <p>"This is to certify that Ms. [Name], Age [X] years, has been examined by me on [Date] and is confirmed to be pregnant. Her expected date of delivery is approximately [Date]. She is advised to begin pre-natal rest from [Start Date]. She will require post-delivery leave as per the Maternity Benefit Act, 1961."</p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">When to Submit the Certificate to HR</h2>
          <p>Timing matters. Most HR departments ask for the maternity leave application with supporting documents <strong>at least 6–8 weeks before the anticipated start of leave</strong>. This gives the company time to arrange for your replacement or workload redistribution.</p>
          <div className="overflow-x-auto mt-3">
            <table className="w-full text-sm border-collapse">
              <thead>
                <tr className="bg-primary/10 text-foreground">
                  <th className="text-left p-3 border border-border font-semibold">Stage</th>
                  <th className="text-left p-3 border border-border font-semibold">Document to Submit</th>
                  <th className="text-left p-3 border border-border font-semibold">When</th>
                </tr>
              </thead>
              <tbody>
                {[
                  ["Pregnancy confirmation", "Gynaecologist's pregnancy certificate", "At the end of 1st trimester (or when comfortable disclosing)"],
                  ["Leave application", "Pre-delivery certificate with EDD", "6–8 weeks before leave start"],
                  ["Post-delivery", "Hospital discharge summary / delivery certificate", "Within 2 weeks of delivery"],
                  ["Return to work", "Fitness certificate (if required by employer)", "On the day of return or 1 week before"],
                ].map(([stage, doc, when]) => (
                  <tr key={stage} className="border border-border">
                    <td className="p-3 border border-border font-medium">{stage}</td>
                    <td className="p-3 border border-border">{doc}</td>
                    <td className="p-3 border border-border">{when}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Maternity Leave for Miscarriage or Medical Termination</h2>
          <p>Under Section 9 of the Maternity Benefit Act, a woman is entitled to <strong>6 weeks of paid leave</strong> following a miscarriage or medical termination of pregnancy (MTP).</p>
          <p className="mt-3">The certificate required is:</p>
          <ul className="list-disc list-inside space-y-1 ml-4 mt-2">
            <li>A medical certificate from the treating doctor or hospital confirming the miscarriage or MTP and the date it occurred</li>
            <li>Hospital discharge summary (if the procedure required hospitalisation)</li>
          </ul>
          <p className="mt-3">This is a sensitive situation. Most HR departments and employers are required by law to treat this documentation with confidentiality.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Government Employees: Additional Requirements</h2>
          <p>Central Government employees are also covered under <strong>Rule 43 of the CCS (Leave) Rules, 1972</strong>, which provides separate maternity leave provisions. For these employees:</p>
          <ul className="list-disc list-inside space-y-2 ml-4 mt-3">
            <li>Maternity leave of 180 days is available for up to two children</li>
            <li>The certificate must come from an "authorised medical attendant" — generally a government hospital doctor or approved panel doctor</li>
            <li>Leave application should be routed through the appropriate administrative channel</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Frequently Asked Questions</h2>
          <div className="space-y-4">
            {[
              { q: "Can my employer reject my maternity leave application?", a: "No. The Maternity Benefit Act, 1961 makes maternity leave a statutory right. An employer cannot legally refuse or penalise you for taking maternity leave. Any termination or adverse action linked to maternity is illegal." },
              { q: "Do I need a doctor's certificate for all 26 weeks of leave?", a: "You typically need documentation at the beginning (EDD certificate) and at delivery (discharge summary). The balance of the 26 weeks flows from the documented dates. Your employer cannot ask you to get a new certificate every week." },
              { q: "What if my delivery is earlier or later than the EDD?", a: "The post-delivery period adjusts accordingly. If delivery is early, pre-delivery leave is shorter but post-delivery leave remains 18 weeks. If late, the pre-delivery period extends." },
              { q: "Is a miscarriage certificate confidential?", a: "Yes. You are legally entitled to keep the medical details private. Your employer needs only the document confirming the event and the dates — not detailed clinical information." },
            ].map(faq => (
              <div key={faq.q} className="bg-muted/50 border border-border rounded-xl p-4">
                <h3 className="font-bold text-sm mb-2 text-foreground">{faq.q}</h3>
                <p className="text-sm">{faq.a}</p>
              </div>
            ))}
          </div>
        </section>

        <div className="bg-primary/5 border border-primary/20 rounded-xl p-5">
          <h3 className="font-bold text-foreground mb-2">Need a Sample Maternity Certificate for HR Training?</h3>
          <p className="text-sm mb-3">Our generator can produce specimen maternity leave certificates for HR onboarding, policy training, and document management system testing.</p>
          <InternalLink href="/generator/formal-cert">→ Generate a Sample Certificate</InternalLink>
        </div>

        <p className="text-sm text-muted-foreground">
          External references:{" "}
          <a href="https://labour.gov.in" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Ministry of Labour and Employment — Maternity Benefit Act</a>
        </p>
        <Disclaimer />
      </div>
    ),
  },

  // ─── ARTICLE 6 ──────────────────────────────────────────────────────────────
  {
    slug: "medical-certificate-college-admission",
    title: "Medical Certificate for College Admission: What It Is and How to Get It",
    metaDescription: "Complete guide to medical certificates required for college admission in India — what colleges ask for, which tests are included, and how to get your fitness certificate quickly.",
    category: "Medical Certificates",
    date: "April 2026",
    readTime: "9 min read",
    tags: ["College Admission", "Medical Certificate", "Students", "India", "Fitness Certificate"],
    author: "Ziven Borceg",
    content: (
      <div className="space-y-6 text-foreground/80 leading-relaxed">
        <p className="text-lg font-medium text-foreground">
          You got the admission. Congratulations! And then you see the admission formalities list — and one item says "Medical Fitness Certificate." Suddenly you're wondering: which doctor do I go to? What tests will I need? How long will it take? And what exactly does the certificate need to say? Don't worry — this guide has all the answers.
        </p>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Why Do Colleges Require a Medical Certificate for Admission?</h2>
          <p>Colleges require a medical fitness certificate for admission for several practical reasons:</p>
          <ul className="list-disc list-inside space-y-2 ml-4 mt-3">
            <li>To ensure students are physically capable of the academic and physical demands of the course</li>
            <li>For courses involving physical activity (sports, nursing, physical education, NCC, NSS)</li>
            <li>For hostel admission — to assess contagious conditions that could affect shared living</li>
            <li>For professional courses (MBBS, BDS, Nursing, Pharmacy, Law) where fitness is a regulatory requirement</li>
            <li>For government-sponsored technical and vocational courses</li>
          </ul>
          <p className="mt-3">In most cases, this is a standard medical fitness certification — not a complex specialist assessment. A visit to any registered MBBS doctor is usually sufficient.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Types of Medical Certificates Colleges May Ask For</h2>
          <div className="space-y-3 mt-3">
            {[
              { type: "General Medical Fitness Certificate", when: "Most UG and PG admissions — confirms you are in general good health and fit to pursue the course" },
              { type: "Physical Fitness Certificate", when: "Physical education, sports, police, defence, and NCC courses — includes physical examination and may require specific fitness benchmarks" },
              { type: "Ophthalmological Certificate", when: "Medical/Nursing/Aviation courses — specifically tests near and distance vision, and colour vision" },
              { type: "Mental Health Fitness Statement", when: "Some clinical and psychology programmes — a very basic declaration of mental health fitness by a registered psychiatrist or physician" },
              { type: "Vaccination Certificate", when: "Medical, nursing, and veterinary programmes — confirms vaccination status (Hepatitis B is usually mandatory)" },
            ].map(d => (
              <div key={d.type} className="bg-card border border-border rounded-lg p-4 flex gap-3">
                <div className="w-2 h-2 rounded-full bg-primary flex-shrink-0 mt-2" />
                <div>
                  <p className="font-semibold text-sm text-foreground">{d.type}</p>
                  <p className="text-xs text-muted-foreground mt-1">{d.when}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">What the Medical Certificate for College Must Contain</h2>
          <p>The standard medical fitness certificate for college admission should include:</p>
          <ul className="list-disc list-inside space-y-2 ml-4 mt-3">
            <li>Doctor's name, qualifications, and NMC/State Council registration number</li>
            <li>Clinic or hospital name, address, and contact</li>
            <li>Student's full name, date of birth, and address</li>
            <li>Date of medical examination</li>
            <li>Statement of fitness: "The student is found medically fit to pursue [Course Name]"</li>
            <li>Any significant findings or conditions (e.g. "requires spectacles for reading")</li>
            <li>Doctor's signature and official stamp</li>
          </ul>
          <p className="mt-3">Some colleges provide their own printed format — check the college website or admission portal for a downloadable form before visiting the doctor.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Step-by-Step: How to Get the Medical Certificate for College Admission</h2>
          <div className="space-y-4 mt-3">
            {[
              { step: "1", title: "Check the College's Specific Requirements", desc: "Download the admission formalities checklist from the college website. Check if they have a specific format or form. Some colleges provide a blank printed form to be filled by the doctor." },
              { step: "2", title: "Collect Your Medical History Documents", desc: "If you have any known conditions, bring relevant reports. This helps the doctor make an informed assessment and fill the certificate accurately." },
              { step: "3", title: "Visit a Registered MBBS Doctor", desc: "Any registered MBBS doctor at a private clinic or government hospital can issue this certificate. For professional medical courses, the college may specify that the certificate must come from a government hospital." },
              { step: "4", title: "Undergo the Examination", desc: "The doctor will check your height, weight, blood pressure, vision, and general health. For most undergraduate admissions, this is a 15–20 minute appointment." },
              { step: "5", title: "Collect the Certificate (Same Day)", desc: "Medical fitness certificates for admission are almost always issued the same day. Check that the doctor has included all required fields and has stamped and signed the document." },
              { step: "6", title: "Attach and Submit Within the Deadline", desc: "Submit with your other admission documents by the college's stated deadline. Keep a photocopy for your own records." },
            ].map(s => (
              <div key={s.step} className="flex gap-4 bg-card border border-border rounded-xl p-4">
                <div className="w-9 h-9 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-sm font-black flex-shrink-0">{s.step}</div>
                <div>
                  <h3 className="font-bold text-foreground mb-1">{s.title}</h3>
                  <p className="text-sm">{s.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Special Requirements for Professional Courses</h2>

          <h3 className="text-xl font-bold text-foreground mb-2 mt-4">MBBS / BDS / Medical Courses</h3>
          <p>Medical Council of India (now NMC) and state medical councils require candidates to be declared fit by a Medical Board in some states. The board typically includes a physician, an ophthalmologist, and sometimes an orthopedic surgeon. Colour blindness can be a disqualifying condition for some specialities.</p>

          <h3 className="text-xl font-bold text-foreground mb-2 mt-4">Nursing Courses</h3>
          <p>The Indian Nursing Council requires candidates to be free from any disability that would prevent safe clinical care. A Hepatitis B vaccination certificate is typically mandatory.</p>

          <h3 className="text-xl font-bold text-foreground mb-2 mt-4">Engineering / Technical Courses</h3>
          <p>For most general engineering admissions, a standard MBBS doctor's fitness certificate is sufficient. Some IITs and NITs have specific physical requirements for certain specialisations.</p>

          <h3 className="text-xl font-bold text-foreground mb-2 mt-4">Law Courses</h3>
          <p>Bar Council of India rules require law students to be physically and mentally fit to practice. A general fitness certificate from an MBBS doctor is usually sufficient.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">When to Use Our Medical Certificate Generator</h2>
          <p>If you're a student who wants to understand what the completed certificate should look like before visiting the doctor — or if you're building a college admission portal and need sample documents for testing — our <InternalLink href="/generator/formal-cert">Medical Certificate Generator</InternalLink> can generate realistic specimen certificates. These are for educational and demonstration use only.</p>
          <p className="mt-3">Also read: <InternalLink href="/blog/medical-certificate-for-school">Medical Certificate for School Absence — A Complete Guide →</InternalLink></p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Frequently Asked Questions</h2>
          <div className="space-y-4">
            {[
              { q: "Can I submit a medical certificate from any private doctor for college admission?", a: "For most courses, yes. For government professional courses (MBBS, BDS, Police, Defence), the college may specify a government hospital. Always check the admission checklist." },
              { q: "What if I have a medical condition — will I be denied admission?", a: "Not necessarily. Most conditions do not bar admission. The college may ask for an additional assessment or may need to provide accommodation. Conditions that prevent safe clinical practice may disqualify for specific medical courses." },
              { q: "How long is the college admission medical certificate valid?", a: "Usually valid for 6–12 months from the date of issue. For reapplying in subsequent years, you may need a fresh certificate." },
              { q: "Do I need separate certificates for hostel admission?", a: "Some colleges issue a combined fitness certificate for both the course and hostel. Others require a separate hostel medical form. Check the hostel admission requirements separately." },
            ].map(faq => (
              <div key={faq.q} className="bg-muted/50 border border-border rounded-xl p-4">
                <h3 className="font-bold text-sm mb-2 text-foreground">{faq.q}</h3>
                <p className="text-sm">{faq.a}</p>
              </div>
            ))}
          </div>
        </section>
        <Disclaimer />
      </div>
    ),
  },

  // ─── ARTICLE 7 ──────────────────────────────────────────────────────────────
  {
    slug: "medical-certificate-form-3-explained",
    title: "Medical Certificate Form 3 Explained: What It Is, When You Need It, and How to Get It",
    metaDescription: "A clear guide to Medical Certificate Form 3 in India — what it is, which laws require it, when you need it, and the step-by-step process to get it from a authorised doctor.",
    category: "Medical Certificates",
    date: "April 2026",
    readTime: "9 min read",
    tags: ["Form 3", "Medical Certificate", "India", "Driving Licence", "Legal"],
    author: "Ziven Borceg",
    content: (
      <div className="space-y-6 text-foreground/80 leading-relaxed">
        <p className="text-lg font-medium text-foreground">
          You've come across a reference to "Medical Certificate Form 3" and you're not sure what it is, who needs it, or where to get it. The term "Form 3" is used in different contexts across India's medical documentation landscape — so the answer depends on the context. This guide covers all the major uses of Form 3 and how to navigate each one.
        </p>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">What Is Medical Certificate Form 3?</h2>
          <p>"Form 3" in a medical certificate context appears in two main situations in India:</p>
          <div className="space-y-3 mt-3">
            <div className="bg-card border border-border rounded-xl p-5">
              <h3 className="font-bold text-foreground mb-2">Context 1: Driving Licence (Motor Vehicles Rules)</h3>
              <p className="text-sm text-muted-foreground">Under some state interpretations and older versions of the Motor Vehicles Rules, "Form 3" was used for medical fitness declarations related to vehicle operation. This has largely been superseded by Form 1 and Form 1A at the national level, but some states may reference "Form 3" in local RTO contexts.</p>
            </div>
            <div className="bg-card border border-border rounded-xl p-5">
              <h3 className="font-bold text-foreground mb-2">Context 2: Persons with Disabilities Act</h3>
              <p className="text-sm text-muted-foreground">Form 3 in the context of disability certification is a certificate of disability issued by a Medical Authority under the Rights of Persons with Disabilities Act, 2016. This is the more commonly required "Form 3" in official government and legal contexts today.</p>
            </div>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Form 3 as a Disability Certificate (RPWD Act, 2016)</h2>
          <p>Under the Rights of Persons with Disabilities Act, 2016, and the Rights of Persons with Disabilities Rules, 2017, a <strong>disability certificate in Form 3</strong> is issued by a "certifying authority" for disabilities not covered by the original Persons with Disabilities Act, 1995.</p>

          <h3 className="text-xl font-bold text-foreground mb-2 mt-4">Who Issues Form 3?</h3>
          <p>Form 3 disability certificates are issued by a <strong>Medical Authority under the RPWD Act</strong>. The certifying authority varies by state and the type of disability, but typically involves:</p>
          <ul className="list-disc list-inside space-y-1 ml-4 mt-2">
            <li>A specialist medical board (for complex conditions)</li>
            <li>A Civil Surgeon or Chief Medical Officer</li>
            <li>A government hospital specialist of the relevant discipline</li>
          </ul>

          <h3 className="text-xl font-bold text-foreground mb-2 mt-4">What Disabilities Does Form 3 Cover?</h3>
          <p>The RPWD Act, 2016 recognised 21 categories of disabilities, including conditions added beyond the original 7. Form 3 covers assessment and certification for many of these including:</p>
          <ul className="list-disc list-inside space-y-1 ml-4 mt-2">
            <li>Autism spectrum disorder</li>
            <li>Intellectual disability</li>
            <li>Specific learning disabilities (dyslexia, dyscalculia)</li>
            <li>Mental illness</li>
            <li>Muscular dystrophy</li>
            <li>Multiple sclerosis</li>
            <li>Parkinson's disease</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">How to Get a Form 3 Disability Certificate</h2>
          <div className="space-y-3 mt-3">
            {[
              { step: "1", title: "Apply Online or at the District Medical Office", desc: "Most states now allow online application on the Unique Disability ID (UDID) portal at udid.gov.in. Alternatively, visit the Chief Medical Officer (CMO) or Civil Surgeon's office in your district." },
              { step: "2", title: "Submit Required Documents", desc: "Identity proof (Aadhaar), address proof, recent medical reports related to your condition, passport-size photographs, and any existing medical records." },
              { step: "3", title: "Medical Board Assessment", desc: "You will be called for an assessment by the relevant specialist(s). For physical disabilities, this may be a single doctor. For complex conditions, a multi-disciplinary board may be involved." },
              { step: "4", title: "Certificate Issuance", desc: "If the board confirms the disability meets the RPWD Act threshold (typically 40% or more disability for most benefits), Form 3 is issued. Processing time varies from a few days to several weeks depending on your state." },
              { step: "5", title: "UDID Card", desc: "Once Form 3 is issued, you can use it to apply for a Unique Disability ID (UDID) card — a national digital ID for persons with disabilities." },
            ].map(s => (
              <div key={s.step} className="flex gap-4 bg-card border border-border rounded-xl p-4">
                <div className="w-9 h-9 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-sm font-black flex-shrink-0">{s.step}</div>
                <div>
                  <h3 className="font-bold text-foreground mb-1">{s.title}</h3>
                  <p className="text-sm">{s.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Benefits Available with a Form 3 Disability Certificate</h2>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>Reservation in government jobs (4% reservation for PwDs)</li>
            <li>Reservation in central government educational institutions</li>
            <li>Income tax deductions under Section 80U of the Income Tax Act</li>
            <li>Concessions on railway travel and bus fares</li>
            <li>Priority in government schemes and welfare programmes</li>
            <li>Accessible housing, scholarships, and assistive device grants</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Key Differences: Form 3, Form 4, and Other Disability Forms</h2>
          <div className="overflow-x-auto mt-3">
            <table className="w-full text-sm border-collapse">
              <thead>
                <tr className="bg-primary/10 text-foreground">
                  <th className="text-left p-3 border border-border font-semibold">Form</th>
                  <th className="text-left p-3 border border-border font-semibold">Purpose</th>
                  <th className="text-left p-3 border border-border font-semibold">Issued By</th>
                </tr>
              </thead>
              <tbody>
                {[
                  ["Form 3", "Disability certificate under RPWD Act 2016", "Medical Board / CMO"],
                  ["Form 4", "Medical certificate for driving licence renewal (some states)", "Registered MBBS doctor"],
                  ["Form 1A", "Medical fitness for driving licence application", "Registered MBBS doctor"],
                  ["Form VII (Disability)", "Certificate for 7 specific disabilities under old PwD Act 1995", "Medical Board / CMO"],
                ].map(([form, purpose, issuedby]) => (
                  <tr key={form} className="border border-border">
                    <td className="p-3 border border-border font-semibold">{form}</td>
                    <td className="p-3 border border-border">{purpose}</td>
                    <td className="p-3 border border-border">{issuedby}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Frequently Asked Questions</h2>
          <div className="space-y-4">
            {[
              { q: "Is Form 3 the same as a disability certificate?", a: "In the context of the RPWD Act, 2016, yes — Form 3 is the format used for disability certification. However, 'Form 3' also appears in driving licence and other regulatory contexts. Always confirm which Form 3 you are being asked for." },
              { q: "Can a private hospital issue a Form 3 disability certificate?", a: "No. Disability certificates under the RPWD Act must be issued by the designated government Medical Authority. Private hospital reports can be used as supporting evidence, but the official Form 3 must come from the authorised government certifying body." },
              { q: "What percentage of disability is needed for a Form 3 certificate?", a: "Most central government benefits require a minimum of 40% disability. However, a disability certificate can be issued for any percentage — some state-level benefits apply at lower thresholds." },
              { q: "How long does Form 3 processing take?", a: "It varies widely — from a few days at efficient district offices to several weeks or months at busy urban centres. The UDID online portal has helped streamline the process in many states." },
            ].map(faq => (
              <div key={faq.q} className="bg-muted/50 border border-border rounded-xl p-4">
                <h3 className="font-bold text-sm mb-2 text-foreground">{faq.q}</h3>
                <p className="text-sm">{faq.a}</p>
              </div>
            ))}
          </div>
        </section>

        <p className="text-sm text-muted-foreground">
          External references:{" "}
          <a href="https://udid.gov.in" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">UDID Portal — Ministry of Social Justice and Empowerment</a>
        </p>
        <Disclaimer />
      </div>
    ),
  },

  // ─── ARTICLE 8 ──────────────────────────────────────────────────────────────
  {
    slug: "medical-certificate-form-4",
    title: "Medical Certificate Form 4: What It Is, Who Needs It, and How to Get It",
    metaDescription: "A clear guide to Medical Certificate Form 4 in India — its use in driving licence renewal, what it contains, which doctor can fill it, and how to get it quickly.",
    category: "Medical Certificates",
    date: "April 2026",
    readTime: "8 min read",
    tags: ["Form 4", "Medical Certificate", "Driving Licence", "India", "RTO"],
    author: "Ziven Borceg",
    content: (
      <div className="space-y-6 text-foreground/80 leading-relaxed">
        <p className="text-lg font-medium text-foreground">
          Medical Certificate Form 4 comes up most often when you're renewing a driving licence for a transport vehicle, or in specific state-level health and administrative contexts. This guide explains exactly what Form 4 is, where it's used, and how to get it without confusion.
        </p>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">What Is Medical Certificate Form 4?</h2>
          <p>In the context of the <strong>Motor Vehicles Act and Rules</strong>, Form 4 is a medical certificate prescribed for specific driving licence-related applications. Like Form 1A, it is a fitness declaration — but it's used in particular circumstances including:</p>
          <ul className="list-disc list-inside space-y-2 ml-4 mt-3">
            <li>Renewal of driving licences for transport vehicles (heavy motor vehicles, buses, trucks)</li>
            <li>Medical fitness certification in some state-level RTO requirements</li>
            <li>Some states continue to use "Form 4" as their local designation for the driving licence medical certificate</li>
          </ul>
          <p className="mt-3">Note: The exact applicability of "Form 4" varies by state. The central Motor Vehicles Rules primarily use Form 1 and Form 1A at the national level — but state transport departments may have their own form numbering. Always verify with your local RTO before visiting a doctor.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">What Form 4 Contains</h2>
          <p>A Form 4 medical certificate for driving purposes typically covers:</p>
          <ul className="list-disc list-inside space-y-2 ml-4 mt-3">
            <li><strong>Applicant's full name, date of birth, address</strong></li>
            <li><strong>Vision test:</strong> Distance vision for both eyes (with/without glasses), colour vision</li>
            <li><strong>Hearing assessment</strong></li>
            <li><strong>Limb examination:</strong> Upper and lower limb mobility</li>
            <li><strong>Cardiovascular and neurological status</strong></li>
            <li><strong>Chronic disease declarations:</strong> Epilepsy, diabetes (insulin-dependent), mental illness</li>
            <li><strong>Fitness declaration:</strong> "Fit/Unfit to drive [vehicle category]"</li>
            <li><strong>Doctor's details:</strong> Name, qualifications, registration number, signature, stamp</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Who Needs Form 4?</h2>
          <div className="overflow-x-auto mt-3">
            <table className="w-full text-sm border-collapse">
              <thead>
                <tr className="bg-primary/10 text-foreground">
                  <th className="text-left p-3 border border-border font-semibold">Situation</th>
                  <th className="text-left p-3 border border-border font-semibold">Form Required</th>
                </tr>
              </thead>
              <tbody>
                {[
                  ["Renewal of light motor vehicle licence (age under 40)", "Usually Form 1 (self-declaration)"],
                  ["Renewal of light motor vehicle licence (age 40+)", "Form 1A or Form 4 (state-specific)"],
                  ["Renewal of transport/commercial vehicle licence", "Form 4 / Form 1A (mandatory)"],
                  ["First-time transport vehicle licence", "Form 1A"],
                  ["Driving licence for HMV (Heavy Motor Vehicle)", "Form 4 / Form 1A"],
                ].map(([situation, form]) => (
                  <tr key={situation} className="border border-border">
                    <td className="p-3 border border-border">{situation}</td>
                    <td className="p-3 border border-border font-medium">{form}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">How to Get Form 4 Filled: Step by Step</h2>
          <div className="space-y-3 mt-3">
            {[
              { step: "1", title: "Get the Form", desc: "Download Form 4 from the Sarathi or Parivahan portal (sarathi.parivahan.gov.in), or obtain a physical copy from your local RTO. Some RTOs also have the form available with authorised doctors." },
              { step: "2", title: "Visit a Registered MBBS Doctor", desc: "Any registered MBBS doctor can fill Form 4. For transport vehicle licences, some RTOs may specify a government hospital or panel doctor. Confirm with your RTO first." },
              { step: "3", title: "Undergo the Medical Examination", desc: "The doctor will test your vision, check blood pressure, assess limb mobility, and ask about chronic conditions. Bring your glasses or hearing aids if applicable." },
              { step: "4", title: "Doctor Completes and Signs Form 4", desc: "The doctor fills all required fields, signs, and stamps the form with their clinic seal. Check that the registration number is clearly written." },
              { step: "5", title: "Submit to RTO with Licence Application", desc: "Attach the completed Form 4 to your driving licence renewal application — physically at the RTO or uploaded on the Sarathi portal, depending on your state." },
            ].map(s => (
              <div key={s.step} className="flex gap-4 bg-card border border-border rounded-xl p-4">
                <div className="w-9 h-9 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-sm font-black flex-shrink-0">{s.step}</div>
                <div>
                  <h3 className="font-bold text-foreground mb-1">{s.title}</h3>
                  <p className="text-sm">{s.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Form 4 vs Form 1A: Key Differences</h2>
          <p>In practice, Form 4 and Form 1A serve very similar purposes and contain nearly identical information. The difference is largely administrative:</p>
          <ul className="list-disc list-inside space-y-2 ml-4 mt-3">
            <li>Form 1A is the central government's prescribed format under the Motor Vehicles Rules, 1989</li>
            <li>Form 4 is used in some state RTOs and older licence renewal systems</li>
            <li>Both require an MBBS doctor's physical examination and certification</li>
            <li>Both cover the same medical parameters (vision, limbs, cardiovascular, neurological)</li>
          </ul>
          <p className="mt-3">Related reading: <InternalLink href="/blog/form-1a-medical-certificate-explained">Medical Certificate Form 1A Explained →</InternalLink></p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-3">Frequently Asked Questions</h2>
          <div className="space-y-4">
            {[
              { q: "How often do I need to renew Form 4 for a transport vehicle licence?", a: "Transport vehicle licences must be renewed every three years, and a fresh medical fitness certificate (Form 4 or equivalent) is required with each renewal." },
              { q: "Can I use Form 1A instead of Form 4?", a: "In most cases yes — they contain the same information. Check with your local RTO to confirm which form they accept. Many RTOs accept both." },
              { q: "What happens if I'm declared unfit on Form 4?", a: "Your driving licence renewal may be rejected. You can seek treatment for the disqualifying condition and reapply after improvement. If you disagree with the assessment, you can seek a second medical opinion." },
              { q: "Is Form 4 required for a two-wheeler renewal?", a: "For light motor vehicles including two-wheelers, a medical certificate is generally not required below the age of 40. Above 40, requirements vary by state." },
            ].map(faq => (
              <div key={faq.q} className="bg-muted/50 border border-border rounded-xl p-4">
                <h3 className="font-bold text-sm mb-2 text-foreground">{faq.q}</h3>
                <p className="text-sm">{faq.a}</p>
              </div>
            ))}
          </div>
        </section>

        <p className="text-sm text-muted-foreground">
          External reference:{" "}
          <a href="https://sarathi.parivahan.gov.in" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">
            Sarathi Parivahan — Driving Licence Portal, Ministry of Road Transport
          </a>
        </p>
        <Disclaimer />
      </div>
    ),
  },
];
